AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An example AWS SAM template for a Lambda function.

Resources:
  ScraperLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: built/index.handler
      Runtime: nodejs18.x
      CodeUri: .
      Timeout: 300
      MemorySize: 2000
